services:
  ruby:
    image: ruby:${RUBY_IMAGE:-3.0}-buster
    environment:
      - HISTFILE=/app/tmp/.bash_history
      - BUNDLE_PATH=/bundle
      - BUNDLE_CONFIG=/app/.bundle/config
    command: bash
    working_dir: /app
    volumes:
      - .:/app:cached
      - bundler_data:/bundle
    tmpfs:
      - /tmp

volumes:
  bundler_data:
